In [1]:
import cv2 
import numpy as np
import os
from sklearn import preprocessing
import matplotlib.pyplot as plt

c:\Users\21379\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [49]:
# data cleaning
def data_elim (image, label, L, newpath, img):
    hist = cv2.calcHist([image], [0], None, [256], [0, 256])
    if (np.where(hist == max(hist))[0][0] != 0) :
        cv2.imwrite(f'{newpath}/{label}_____{img}', image)
    else :
        if(max(hist)/(image.shape[0]*image.shape[1])<0.7):
            cv2.imwrite(f'{newpath}/{label}_____{img}', image)
        else:
            L.append(label)

def data_clean(old_path, new_path, data_elim, datacleaned):
    for root, dir, images in os.walk(old_path):
        for img in images:
            if ((img.endswith('jpg')) or (img.endswith('bmp')) or (img.endswith('png'))) and (not((img.endswith(').jpg')) or (img.endswith(').bmp')))) :       
                path= os.path.join(root, img)
                label = img[:5]
                imag = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

                if len(imag) != 0 :
                    imag= cv2.resize(imag, (128,128) , interpolation = cv2.INTER_AREA)
                    data_elim(imag,label , datacleaned, new_path, img)
    return datacleaned

In [44]:
x = []
y = []
for root, dir, images in os.walk('cleaned'):
    for img in images:
        x.append(img)
        y.append(img[0:5])

le = preprocessing.LabelEncoder()
z = list(le.fit_transform(y))

labels_dic= {k:v for k,v in zip(y,z)}
len(x)

7590

In [39]:
np.unique(z, return_counts=True) 

(array([   0,    1,    2, ..., 2005, 2006, 2007], dtype=int64),
 array([ 3,  2,  1, ...,  5, 10, 10], dtype=int64))

In [45]:
d = [i for i,k in zip(x , z) if z.count(k)>1]

# z.count(1256)
print(len(d))

6385


In [47]:
for root, dir, images in os.walk('cleaned'):
    for img in images:
        if img in d :       
            path= os.path.join(root, img)
            image = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
            cv2.imwrite(f'cleaned/classunique/{img}', image)

In [48]:
v=[]
for root, dir, images in os.walk('cleaned/classunique'):
    for img in images:
        v.append(img)
len(v)

6385

In [15]:
casia800 = []
for root, dir, images in os.walk('cleaned/casia800'):
    for img in images:
        casia800.append(img[0:5])
casia800 = np.array(casia800)
np.unique(casia800, return_counts=True)   # nbr de classes  108   bin casiaaa w mmu
# # plt.scatter(f1,n1)
# # plt.show()
# plt.hist(casia800)

(array(['S2001', 'S2002', 'S2003', 'S2004', 'S2005', 'S2006', 'S2007',
        'S2008', 'S2009', 'S2010', 'S2011', 'S2012', 'S2013', 'S2014',
        'S2015', 'S2016', 'S2017', 'S2018', 'S2019', 'S2020', 'S3001'],
       dtype='<U5'),
 array([38, 40, 37, 39, 33, 39, 40, 20, 39, 37, 24, 39, 38, 37, 37, 36, 24,
        35, 34, 29,  8], dtype=int64))

In [7]:
s2=[]
for root, dir, images in os.walk('cleaned'):
    for img in images:
        if img.startswith('S2002') :
            s2.append(img)
print(s2)

['S2002_____S2002L01.jpg', 'S2002_____S2002L02.jpg', 'S2002_____S2002L03.jpg', 'S2002_____S2002L04.jpg', 'S2002_____S2002L05.jpg', 'S2002_____S2002L06.jpg', 'S2002_____S2002L07.jpg', 'S2002_____S2002L08.jpg', 'S2002_____S2002L09.jpg', 'S2002_____S2002L10.jpg', 'S2002_____S2002L11.jpg', 'S2002_____S2002L12.jpg', 'S2002_____S2002L13.jpg', 'S2002_____S2002L14.jpg', 'S2002_____S2002L15.jpg', 'S2002_____S2002L16.jpg', 'S2002_____S2002L17.jpg', 'S2002_____S2002L18.jpg', 'S2002_____S2002L19.jpg', 'S2002_____S2002L20.jpg', 'S2002_____S2002R01.jpg', 'S2002_____S2002R02.jpg', 'S2002_____S2002R03.jpg', 'S2002_____S2002R04.jpg', 'S2002_____S2002R05.jpg', 'S2002_____S2002R06.jpg', 'S2002_____S2002R07.jpg', 'S2002_____S2002R08.jpg', 'S2002_____S2002R09.jpg', 'S2002_____S2002R10.jpg', 'S2002_____S2002R11.jpg', 'S2002_____S2002R12.jpg', 'S2002_____S2002R13.jpg', 'S2002_____S2002R14.jpg', 'S2002_____S2002R15.jpg', 'S2002_____S2002R16.jpg', 'S2002_____S2002R17.jpg', 'S2002_____S2002R18.jpg', 'S2002_____

In [19]:
f , n = np.unique(y, return_counts=True) 
# plt.figure(figsize=(25,25)) 
# plt.plot(f,n)
# plt.show()


# print(n.argmax())
maxi = [k for (k,v) in labels_dic.items() if v == np.where(n == 1)[0][0]]
print(maxi)

['001_1']
